### ISSUE TITLE
Which repository should we be tracking/is being updated – this or @substack’s?

### ISSUE THREAD

**Issue by aral** [random-access-storage/random-access-idb#3]
Hey there, which repo is the “official” one, as it were? This or @substack’s original?

Thanks :)

**Comment by soyuka** [comment]
This is a fork where we implemented the `random-access-storage` abstraction :). 

Feel free to use either one, their usage should be the same unless you need that abstraction! For example `random-access-network` works well with random-access modules that are using the storage abstraction, it's why I forked it in the first place!  

/note to self: should mention this in the readme

**Comment by aral** [comment]
@soyuka Ah, thanks, Antoine. Appreciate the clarification (and yes, this would be good to have in the readme) :)

**Comment by soyuka** [comment]
https://github.com/random-access-storage/random-access-idb/commit/32fb1cc47efab55060513eb310bceadebc4cb710
