### ISSUE TITLE
use npm scoped packages 

### ISSUE THREAD

**Issue by austinfrey** [random-access-storage/random-access-idb#5]
This might be a broader topic for the github org,  but since there are a few different random-access-idb modules, would it make sense to use scoped packages for these modules for clarity? i.e. `@random-access-storage/random-access-idb`

**Comment by nikugogoi** [comment]
I think it is a suggestion to be discussed. There is a lot of difference between this and https://github.com/substack/random-access-idb. And this repo is a lot more suitable for use with `random-access-storage` instances.
